# working_directory = "/users/gagep" # Use on windows.

[colors]
transparent_background_colors = true

[font]
normal = {family = "IMWritingMono Nerd Font Mono"}

[keyboard]
bindings = [
    {key = "q", mods = "Control|Shift", action = "Quit"},
    {key = "w", mods = "Control|Shift", action = "Quit"},
    {key = "n", mods = "Control|Shift", action = "CreateNewWindow"},
]
