working_directory = "/users/gagep"

[colors]
transparent_background_colors = true

[font]
normal = {family = "IMWritingMono Nerd Font Mono"}

[keyboard]
bindings = [
    { key = "Enter", mods = "Control", chars = "\u000D"},
    {key = "q", mods = "Control|Shift", action = "Quit"},
    {key = "w", mods = "Control|Shift", action = "Quit"},
    {key = "Tab", mods = "Control", action = "ReceiveChar"},
]
